[package]
name = "textmode"
version = "0.1.0"
authors = ["Andy Herbert <andy.herbert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "tmode"
path = "src/bin/tmode.rs"
